import type { OfficeRole } from "@/features/office/types";

export type { OfficeRole } from "@/features/office/types";

export const officePermissionValues = [
  "dashboard.read",
  "crm.read",
  "crm.write",
  "crm.assign",
  "land.read",
  "land.write",
  "land.review",
  "projects.read",
  "projects.write",
  "projects.manage",
  "tasks.read",
  "tasks.write",
  "tasks.assign",
  "finance.read",
  "finance.write",
  "finance.approve",
  "finance.post",
  "payments.record",
  "payments.post",
  "expenses.read",
  "expenses.write",
  "expenses.approve",
  "approvals.read",
  "approvals.decide",
  "documents.read",
  "documents.write",
  "documents.review",
  "reports.read",
  "team.read",
  "team.manage",
  "audit.read",
  "settings.manage",
] as const;

export type OfficePermission = (typeof officePermissionValues)[number];

const allPermissions: readonly OfficePermission[] = officePermissionValues;

export const officePermissions = {
  owner: allPermissions,
  admin: allPermissions,
  manager: [
    "dashboard.read",
    "crm.read",
    "crm.write",
    "crm.assign",
    "land.read",
    "land.write",
    "land.review",
    "projects.read",
    "projects.write",
    "projects.manage",
    "tasks.read",
    "tasks.write",
    "tasks.assign",
    "finance.read",
    "finance.write",
    "finance.approve",
    "finance.post",
    "payments.record",
    "payments.post",
    "expenses.read",
    "expenses.write",
    "expenses.approve",
    "approvals.read",
    "approvals.decide",
    "documents.read",
    "documents.write",
    "documents.review",
    "reports.read",
    "team.read",
    "audit.read",
  ],
  sales: [
    "dashboard.read",
    "crm.read",
    "crm.write",
    "land.read",
    "projects.read",
    "tasks.read",
    "tasks.write",
    "documents.read",
    "documents.write",
  ],
  projects: [
    "dashboard.read",
    "crm.read",
    "land.read",
    "land.write",
    "projects.read",
    "projects.write",
    "projects.manage",
    "tasks.read",
    "tasks.write",
    "tasks.assign",
    "expenses.read",
    "expenses.write",
    "approvals.read",
    "documents.read",
    "documents.write",
    "documents.review",
    "reports.read",
  ],
  accounts: [
    "dashboard.read",
    "crm.read",
    "projects.read",
    "tasks.read",
    "tasks.write",
    "finance.read",
    "finance.write",
    "payments.record",
    "expenses.read",
    "expenses.write",
    "approvals.read",
    "documents.read",
    "documents.write",
    "reports.read",
  ],
  viewer: [
    "dashboard.read",
    "crm.read",
    "land.read",
    "projects.read",
    "tasks.read",
    "finance.read",
    "expenses.read",
    "documents.read",
    "reports.read",
  ],
} as const satisfies Record<OfficeRole, readonly OfficePermission[]>;

export function hasOfficePermission(role: OfficeRole, permission: OfficePermission): boolean {
  const permissions: readonly OfficePermission[] = officePermissions[role];
  return permissions.includes(permission);
}
