; Abdullah Properties Office overrides for Tauri-specific NSIS messages.
LangString addOrReinstall ${LANG_ENGLISH} "Repair or reinstall Abdullah Properties Office"
LangString alreadyInstalled ${LANG_ENGLISH} "Abdullah Properties Office is already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed for this Windows account. Choose a maintenance option, then select Next."
LangString appRunning ${LANG_ENGLISH} "${PRODUCTNAME} is open. Close the application before continuing."
LangString appRunningOkKill ${LANG_ENGLISH} "${PRODUCTNAME} is open.$\nSelect OK to close it safely before setup continues."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose whether to repair the application files or remove the current installation."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how to continue with ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Keep the current installation"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Keep the current installation (downgrades are blocked)"
LangString failedToKillApp ${LANG_ENGLISH} "Setup could not close ${PRODUCTNAME}. Close it manually and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Preparing the secure Windows desktop runtime..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed. Downgrades are blocked to protect application compatibility and local data."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is installed. Review the maintenance choice before continuing. Local office data is preserved by default."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are blocked. Use an approved newer installer or the graphical maintenance workflow.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "The current installation could not be removed. No success state has been recorded."
LangString uninstallApp ${LANG_ENGLISH} "Remove ${PRODUCTNAME} application files"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Remove the current application files before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "The required Windows WebView2 runtime could not be prepared. Restart setup or contact Abdullah Properties support."
LangString webview2DownloadError ${LANG_ENGLISH} "The Windows WebView2 runtime download failed (code $0). Check the connection and try again."
LangString webview2DownloadSuccess ${LANG_ENGLISH} "The Windows WebView2 runtime was downloaded successfully."
LangString webview2Downloading ${LANG_ENGLISH} "Downloading the required Windows WebView2 runtime..."
LangString webview2InstallError ${LANG_ENGLISH} "The Windows WebView2 runtime installation failed with code $1."
LangString webview2InstallSuccess ${LANG_ENGLISH} "The Windows WebView2 runtime is ready."
LangString deleteAppData ${LANG_ENGLISH} "Also permanently delete local drafts, queued work and settings (irreversible)"
